<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All CategoriesPHONES  T</name>
   <tag></tag>
   <elementGuidId>ea6fe940-e7ba-4669-8ab0-fbb6a357dc55</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search.category</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select Category</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All CategoriesPHONES &amp; TABLETS  Mobile Phones  Tablets  Mobile AccessoriesELECTRONICS  Televisions  TV Accessories  Home Audio  Computers  Cameras &amp; AccessoriesHOME APPLIANCES  Large Appliances  Small Appliances  Kitchen Appliances  Kitchen &amp; DiningFOOD &amp; DRINKS  Beverages  Grains &amp; Flour  Cooking Fats &amp; Oils  Jams, Honey &amp; Spreads  Spices &amp; Sauces  Confectionery  Breakfast Cereals  Nutrition &amp; Supplements  Pasta &amp; Noodles  TinsHOME CARE  Air Fresheners  Pesticides &amp; Insecticides  Detergent &amp; Cleaners  Tissues &amp; Disposables  Cleaning Tools  Detergents &amp; CleanersPERSONAL CARE  Bath &amp; Body  Feminine Hygiene  Oral Care  Men's Grooming  PerfumesBEAUTY  Hair &amp; Haircare  Make Up &amp; Nail Care  WatchesBABY &amp; KIDS  Diapering  Baby Gear  Baby Toiletries &amp; Bath Time  Baby FeedingALCOHOLIC BEVERAGES  Wine  Spirits  BeerEXPRESS DELIVERY  Express Alcohol Delivery!  Gift CardsSamsungTecnoAppleHTCSonyL.A ColorsHPLenovoEABLVonBruhmArmcoSaturnMobile Accessories</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search.category&quot;)</value>
   </webElementProperties>
</WebElementEntity>
